[package]
name = "dummy_wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mult"
path = "src/mult.rs"
crate-type = ["cdylib", "lib"]


[build-dependencies]
cc = "1.0"
bindgen = "0.69.4"