#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
/* automatically generated by rust-bindgen 0.69.4 */

pub type int8 = ::std::os::raw::c_char;
pub type uint8 = ::std::os::raw::c_uchar;
pub type int32 = ::std::os::raw::c_int;
pub type uint32 = ::std::os::raw::c_uint;
extern "C" {
    pub fn add(x: uint32, y: uint32) -> uint32;
}
extern "C" {
    pub fn mult(x: uint32, y: uint32) -> uint32;
}
extern "C" {
    pub fn poww(base: uint32, exponent: uint8) -> uint32;
}
